name: 'Setup Rust environment'
description: 'Setup a Rust environment and add it to the PATH, additionally providing custom target support'
author: 'Raphaël Thériault'
branding:
  icon: 'code'
  color: 'orange'
inputs:
  rust-channel:
    description: 'Rust channel (version) to use (defaults to stable)'
    default: ''
  rust-host:
    description: 'Rust host to use (defaults to current platform)'
    default: ''
  rust-target:
    description: 'Rust target to compile for (defaults to none)'
    default: ''
  cache:
    description: 'Enable caching (anything but ''true'' defaults to ''false'')'
    default: 'true'
  install-rustfmt:
    description: 'Install rustfmt (anything but ''true'' defaults to ''false'')'
    default: 'false'
  install-clippy:
    description: 'Install clippy (anything but ''true'' defaults to ''false'')'
    default: 'false'
  install-cross:
    description: 'Install cross (anything but ''true'' defaults to ''false'')'
    default: 'false'
runs:
  using: 'node12'
  main: 'lib/main.js'
